"""
wiki_generator/pipeline.py — Transform completed task history into LLM-Wiki Markdown.

Wiki files are written to wiki/<domain>/<YYYY-MM-DD>_<task_id>.md and committed
to Git so the repo accumulates architecture decisions and troubleshooting records.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from core.graph_state import OrchestratorState, Task

WIKI_DIR = Path("wiki")

# Map keywords in task descriptions to domain subdirectories
DOMAIN_KEYWORDS: dict[str, list[str]] = {
    "infra":        ["docker", "kubernetes", "k8s", "ollama", "gpu", "vram", "install"],
    "orchestration":["langgraph", "state", "routing", "agent", "node", "task"],
    "devops":       ["ci", "cd", "pipeline", "deploy", "git", "push", "pull", "commit"],
    "troubleshoot": ["error", "fail", "exception", "fix", "debug", "issue", "broken"],
    "architecture": ["design", "decision", "adr", "refactor", "schema", "interface"],
}


def infer_domain(description: str) -> str:
    desc_lower = description.lower()
    for domain, keywords in DOMAIN_KEYWORDS.items():
        if any(kw in desc_lower for kw in keywords):
            return domain
    return "general"


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:60]


def _utc_date() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _format_task_entry(task: "Task") -> str:
    status_badge = "✅" if task.status.value == "completed" else "❌"
    assigned = task.assigned_to.value if task.assigned_to else "unassigned"
    complexity_label = (
        "High" if task.complexity_score >= 7
        else "Medium" if task.complexity_score >= 4
        else "Low"
    )

    return f"""\
# {task.description}

> **Task ID:** `{task.task_id}`
> **Status:** {status_badge} {task.status.value}
> **Assigned to:** {assigned}
> **Complexity:** {complexity_label} ({task.complexity_score}/10)
> **Created:** {task.created_at}
> **Completed:** {task.updated_at}

## Result

```
{task.result or "No result recorded."}
```

## Context

- This task was routed to `{assigned}` based on complexity score {task.complexity_score}/10.
- Routing policy: score ≥7 → Deputy only, 4–6 → Deputy preferred, 0–3 → Worker.

---
*Auto-generated by llm-wiki-to-init-agents-ochestration wiki pipeline.*
"""


def generate_wiki_entries(
    tasks: "list[Task]",
    state: "OrchestratorState",
) -> list[Path]:
    """
    Write one Markdown file per task. Returns list of created file paths
    (for the caller to include in the git commit).
    """
    created: list[Path] = []
    date_str = _utc_date()

    for task in tasks:
        domain = infer_domain(task.description)
        domain_dir = WIKI_DIR / domain
        domain_dir.mkdir(parents=True, exist_ok=True)

        filename = f"{date_str}_{_slug(task.task_id)}.md"
        wiki_file = domain_dir / filename

        wiki_file.write_text(_format_task_entry(task))
        created.append(wiki_file)

    if created:
        _update_index(state)
        created.append(WIKI_DIR / "INDEX.md")

    return created


def _update_index(state: "OrchestratorState") -> None:
    """Regenerate wiki/INDEX.md with a summary of all generated entries."""
    index_path = WIKI_DIR / "INDEX.md"
    WIKI_DIR.mkdir(parents=True, exist_ok=True)

    domain_sections: dict[str, list[str]] = {}
    for md_file in sorted(WIKI_DIR.rglob("*.md")):
        if md_file.name == "INDEX.md":
            continue
        domain = md_file.parent.name
        rel = md_file.relative_to(WIKI_DIR)
        domain_sections.setdefault(domain, []).append(f"- [{md_file.stem}]({rel})")

    lines = [
        "# LLM-Wiki Index",
        "",
        f"> Generated: {datetime.now(timezone.utc).isoformat()}",
        f"> Session: `{state.session_id}`",
        f"> Total entries: {state.wiki_entries_generated}",
        "",
    ]
    for domain, entries in sorted(domain_sections.items()):
        lines.append(f"## {domain.capitalize()}")
        lines.extend(entries)
        lines.append("")

    index_path.write_text("\n".join(lines))
